services:
  phpfpm-arm64:
    # image: arm64v8/php:8.0-fpm-alpine3.13
    build: .
    volumes:
      # - ./config/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./config/etc:/usr/local/etc
      - ./app:/app
    ports:
      - "9000:9000"