services:
  phpfpm-arm64:
    image: l3043y/phpfpm-arm64
    # image: arm64v8/php:8.0-fpm-alpine3.13
    # build: .
    volumes:
      - ./config/etc:/usr/local/etc
      - ./app:/app
    ports:
      - "9000:9000"
